wedding/guests/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_required
from wedding import db
from wedding.models import Invitation
from wedding.guests.forms import InvitationForm, GuestSearchForm, RSVPForm
from sqlalchemy import func


guests = Blueprint('guests', __name__)

@guests.route("/rsvp", methods=['GET', 'POST'])
def rsvp():
    form = GuestSearchForm()
    if form.validate_on_submit():
        search_name = "%" + form.search.data + "%"
        invitations = Invitation.query.filter(Invitation.name.like(search_name)).all()
        if invitations:
            return render_template('rsvp.html', form=form, invitations=invitations)
        else:
            flash('Unsuccessful. Please reach out to the couple to see exactly how they entered your details.', 'danger')
    return render_template('rsvp.html', form=form)



@guests.route("/rsvp/<int:invitation_id>/update", methods=['GET', 'POST'])
def update_attendance(invitation_id):
    invitation = Invitation.query.get_or_404(invitation_id)
    form = RSVPForm()
    if form.validate_on_submit():
        invitation.party_size = form.party_size.data
        invitation.attending_to_ceremony = form.attending_to_ceremony.data
        invitation.attending_to_reception = form.attending_to_reception.data
        db.session.commit()
        flash('Thank you!', 'success')
        return redirect(url_for('main.home')) 
    elif request.method == 'GET':
        name = invitation.name
        form.party_size.data = invitation.party_size
        form.attending_to_ceremony.data = invitation.attending_to_ceremony
        form.attending_to_reception.data = invitation.attending_to_reception
    return render_template('update_attendance.html', form=form, name=name)


@guests.route("/guest-list")
@login_required
def guest_list():
    total_c = db.session.query(func.sum(Invitation.party_size)).filter(Invitation.attending_to_ceremony==True).one()[0]
    total_r = db.session.query(func.sum(Invitation.party_size)).filter(Invitation.attending_to_reception==True).one()[0]
    page = request.args.get('page', 1, type=int)
    invitations = Invitation.query.paginate(page=page, per_page=7)
    return render_template('guest_list.html', invitations=invitations, total_r=total_r, total_c=total_c)


@guests.route("/guest/new", methods=['GET', 'POST'])
@login_required
def new_invitation():
    form = InvitationForm()
    if form.validate_on_submit():
        invitation = Invitation(name=form.name.data)
        db.session.add(invitation)
        db.session.commit()
        flash('You added a new guest', 'success')
        return redirect(url_for('guests.guest_list'))
    return render_template('create_invitation.html', form=form, legend='Add Guest')


@guests.route("/guest/<int:invitation_id>/update", methods=['GET', 'POST'])
@login_required
def update_invitation(invitation_id):
    invitation = Invitation.query.get_or_404(invitation_id)
    form = InvitationForm()
    if form.validate_on_submit():
        invitation.name = form.name.data
        db.session.commit()
        flash('Your invitation has been updated!', 'success')
        return redirect(url_for('guests.guest_list'))
    elif request.method == 'GET':
        form.name.data = invitation.name
    return render_template('create_invitation.html', form=form, legend='Update Guest')


@guests.route("/guest/<int:invitation_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_invitation(invitation_id):
    invitation = Invitation.query.get_or_404(invitation_id)
    db.session.delete(invitation)
    db.session.commit()
    flash('Your invitation has been deleted!', 'success')
    return redirect(url_for('guests.guest_list'))

wedding/posts/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import login_required
from wedding import db
from wedding.models import Post
from wedding.posts.forms import PostForm


posts = Blueprint('posts', __name__)

@posts.route("/guest-book")
def guest_book():
    page = request.args.get('page', 1, type=int)
    book = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=6)
    return render_template('guest_book.html', book=book)


@posts.route("/post/new", methods=['GET', 'POST'])
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(content=form.content.data, author=form.author.data)
        db.session.add(post)
        db.session.commit()
        flash('You added a new post', 'success')
        return redirect(url_for('posts.guest_book'))
    return render_template('create_post.html', form=form, legend='Add Post')


@posts.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('posts.guest_book'))

wedding/songs/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import login_required
from wedding import db
from wedding.models import Song
from wedding.songs.forms import SongForm

songs = Blueprint('songs', __name__)

@songs.route("/song-request")
def song_request():
    page = request.args.get('page', 1, type=int)
    song_list = Song.query.paginate(page=page, per_page=7)
    return render_template('song_request.html', song_list=song_list)

@songs.route("/song/new", methods=['GET', 'POST'])
def new_song():
    form = SongForm()
    if form.validate_on_submit():
        song = Song(name=form.name.data, artist=form.artist.data)
        db.session.add(song)
        db.session.commit()
        flash('You added a new song', 'success')
        return redirect(url_for('songs.song_request'))
    return render_template('add_song.html', form=form, legend='Add Song')


@songs.route("/song/<int:song_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_song(song_id):
    song = Song.query.get_or_404(song_id)
    db.session.delete(song)
    db.session.commit()
    flash('Your song has been deleted!', 'success')
    return redirect(url_for('songs.song_request'))

wedding/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from wedding import db, bcrypt
from wedding.models import User
from wedding.users.forms import RegistrationForm, LoginForm

users = Blueprint('users', __name__)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

wedding/templates/add_person.html
{% extends "layout.html" %}

{% block header %}
    <h2>{{ legend }}</h2>
{% endblock header %}

{% block content %}
<div class="wow fadeInUp">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.role.label(class="form-control-label") }}
                {{ form.role(class="form-control form-control-lg") }}
            </div>
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.gender.label(class="form-control-label") }}
                {{ form.gender(class="form-control form-control-lg") }}
            </div>
            
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

wedding/templates/add_song.html
{% extends "layout.html" %}

{% block header %}
    <h2>{{ legend }}</h2>
{% endblock header %}

{% block content %}
<div class="wow fadeInUp">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.artist.label(class="form-control-label") }}
                {% if form.artist.errors %}
                    {{ form.artist(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.artist.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.artist(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

wedding/templates/create_invitation.html
{% extends "layout.html" %}

{% block header %}
    <h2>{{ legend }}</h2>
{% endblock header %}

{% block content %}
<div class="wow fadeInUp">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

wedding/templates/create_post.html
{% extends "layout.html" %}

{% block header %}
    <h2>{{ legend }}</h2>
{% endblock header %}

{% block content %}
<div class="wow fadeInUp">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.author.label(class="form-control-label") }}
                {% if form.author.errors %}
                    {{ form.author(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.author.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.author(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

wedding/templates/guest_book.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}">
{% endblock css %}

{% block header %}
      <h2>Guest Book</h2>
      <p>Please leave well wishes for the new Mr and Mrs. </p>
{% endblock header %}

{% block content %}
    <div class="wow fadeInUp">
    <div class="float-right"> 
      <a type="button" class="btn btn-info" href="{{ url_for('posts.new_post') }}"><i class="fa fa-plus"></i> Add New</a>   
    </div>
    <div class="row align-items-center">
    {% for post in book.items %}
      <div class="col-md-6 wow fadeInUp" data-wow-delay="0.1s"" >
          {% if current_user.is_authenticated %}
            <div class="float-right">
                <a title="Delete" class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('posts.delete_post', post_id=post.id) }}"><i class="fa fa-trash"></i></a>
              </div>
          {% endif %}
        <article class="media content-section">
          <div class="media-body">
            <p class="article-content">{{ post.content }}</p>
            <div class="article-metadata">
              <small class="mr-2" href="#">{{ post.author}}</small>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
          </div>
        </article>
      </div>
    {% endfor %}
  </div>
   {% for page_num in book.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if book.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('posts.guest_book', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('posts.guest_book', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

wedding/templates/guest_list.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}">
{% endblock css %}

{% block header %}
    <h2>Guest List</h2>
{% endblock header %}

{% block content %}



  <div class="wow fadeInUp">
    <div class="float-right">
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#totalsModal">
        Show totals
      </button>  
      <a type="button" class="btn btn-info" href="{{ url_for('guests.new_invitation') }}"><i class="fa fa-plus"></i> Add New</a>   
    </div>
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Party Size</th>
          <th scope="col">Ceremony</th>
          <th scope="col">Reception</th>
          <th scope="col">Options</th>
        </tr>
      </thead>
      <tbody>
      {% for invitation in invitations.items %}
        <tr >
          <td>{{ invitation.id }}</td>
          <td>{{ invitation.name }}</td>
          <td>{{ invitation.party_size }}</td>
          <td>
            {% if invitation.attending_to_ceremony %}
              <i class="fa fa-check"></i>
            {% else %}
              <i class="fa fa-times"></i>
            {% endif %}
          </td>
          <td>
            {% if invitation.attending_to_reception %}
              <i class="fa fa-check"></i>
            {% else %}
              <i class="fa fa-times"></i>
            {% endif %}
          </td>
          <td>
            <a title="Edit" class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('guests.update_invitation', invitation_id=invitation.id) }}"><i class="fa fa-pencil"></i></a>
            <a title="Delete" class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('guests.delete_invitation', invitation_id=invitation.id) }}"><i class="fa fa-trash"></i></a>
          </td>
        </tr>
      {% endfor %}
          
      </tbody>
      </table>

    </div>
    {% for page_num in invitations.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if invitations.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('guests.guest_list', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('guests.guest_list', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

        <div class="wow fadeInUp total-guests float-left">
  <h3>Total guests</h3>
    <div class="row justify-content-center"">
    <p>For ceremony: {{total_c}}</p>
    <p>     For reception: {{total_r}}</p>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="totalsModal" tabindex="-1" role="dialog" aria-labelledby="totalsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="totalsModalLabel">Total Guests</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center"">
          <p>For ceremony: {{total_c}}</p>
          <p>For reception: {{total_r}}</p>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

wedding/templates/home.html
{% extends "layout.html" %}
{% block content %}

		<!--<img src="{{ url_for('static', filename='img/family.JPEG') }}" class="img-fluid" alt="Responsive image">
		-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	</ol>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/family.JPEG') }}" alt="Our family">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/fun.JPG') }}" alt="Made for each other">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/kiss.JPG') }}" alt="Kiss">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/walk.JPG') }}" alt="and they lived happily ever after">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/ring.JPG') }}" alt="The ring">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/back.JPG') }}" alt="Kissing under tree">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/smile.JPG') }}" alt="You know it's love when all you want is that person to be happy,">
		</div>
		<div class="carousel-item">
			<img class="d-block w-100" src="{{ url_for('static', filename='img/tree.jpg') }}" alt="Always together">
		</div>
	</div>
	<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

{% endblock content %}

{% block js %}
{% endblock js %}

wedding/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  	<meta charset="utf-8">
  	<title>Ana and Kevin Wedding</title>
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">


  	<!-- Google Fonts -->
  	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700">

  	<!-- Bootstrap Files -->
  	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lib/bootstrap/css/bootstrap.min.css') }}">

  	<!-- Libraries CSS Files -->
  	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lib/animate/animate.min.css') }}">
  	{% block css %}{% endblock %}

  	<!-- Main Stylesheet File -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

</head>

<body>

	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="#">
				<img src="{{ url_for('static', filename='img/logo.png') }}" width="60" height="60" alt="">
			 </a>
			 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
	    		<span class="navbar-toggler-icon"></span>
	  		</button>
		  	<div class="collapse navbar-collapse" id="navbarText">
		    	<ul class="navbar-nav mr-auto">
		      		<li class="nav-item active">
		        		<a class="nav-link" href="/home">Home <span class="sr-only">(current)</span></a>
		      		</li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="/schedule">Schedule</a>
		      		</li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="/wedding-party">Wedding Party</a>
		      		</li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="/guest-book">Guest Book</a>
		      		</li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="/song-request">Song Request</a>
		      		</li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="/rsvp">RSVP</a>
		      		</li>
		    	</ul>
		    	{% if current_user.is_authenticated %}
		    		<div class="navbar-nav">
			    		<a class="nav-item nav-link" href="{{ url_for('guests.guest_list') }}">Guest List </a>
			    		<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout </a>
		    		</div>
		    	{% else %}
			    	<span class="navbar-text d-none d-lg-block">
			      		#MAYdForEachOther
			    	</span>
			    {% endif %}
		  	</div>
		</nav>
	</header>

	<!-- Content -->
	<div>
		<main role="main" class="container">
			{% with messages = get_flashed_messages(with_categories=true) %}
            	{% if messages %}
              		{% for category, message in messages %}
                		<div class="alert alert-{{ category }}">
                  			{{ message }}
                		</div>
              		{% endfor %}
            	{% endif %}
			{% endwith %}
  			<div class="section-header">
				{% block header %}{% endblock %}
			</div>

      		{% block content %}{% endblock %}

        </main>

	</div>

	<!-- JavaScript Libraries -->
  	<script type="text/javascript" src="{{ url_for('static', filename='lib/jquery/jquery.min.js') }}"></script>
  	<script type="text/javascript" src="{{ url_for('static', filename='lib/jquery/jquery-migrate.min.js') }}"></script>
  	<script type="text/javascript" src="{{ url_for('static', filename='lib/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  	<script type="text/javascript" src="{{ url_for('static', filename='lib/wow/wow.min.js') }}"></script>
  	{% block js %}{% endblock %}

  	<!-- Template Main Javascript File -->
  	<script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>
</html>

wedding/templates/rsvp.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}">
{% endblock css %}

{% block header %}
			<h2>RSVP</h2>
			<p>Please let us know your plans here. We hope we get to celebrate together!</p>
{% endblock header %}

{% block content %}

{% if invitations %}
<div class="wow fadeInUp">
<h5>Select your invitation</h5>
	<div class="table-responsive">
	  <table class="table">
	    <thead>
	      <tr>
	        <th scope="col">Name on Invitation</th>
	        <th scope="col">Options</th>
	      </tr>
	    </thead>
	    <tbody>
	    {% for invitation in invitations %}
	      <tr >
	        <td>{{ invitation.name }}</td>
	        <td>
	          <a title="Edit" class="btn btn-info btn-sm mt-1 mb-1" href="{{ url_for('guests.update_attendance', invitation_id=invitation.id) }}"><i class="fa fa-hand-pointer-o"></i></a>
	        </td>
	      </tr>
	    {% endfor %}
	    </tbody>
	  </table>
	 </div>
</div>

{% else %}

<div class="wow fadeInUp">
    <form  method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="col-xs-12 col-sm-10 offset-md-2 col-md-6 offset-md-3">
                {{ form.search.label(class="form-control-label") }}
                {% if form.search.errors %}
                    {{ form.search(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.search.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.search(class="form-control form-control-lg", placeholder="Ex. Daniel Smith (not Dr. or Mr. Smith)") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endif %}

{% endblock content %}

wedding/templates/song_request.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/font-awesome/css/font-awesome.min.css') }}">
{% endblock css %}

{% block header %}
      <h2>Song Request</h2>
      <p>Any song that you would love to dance? </p>
{% endblock header %}

{% block content %}
    <div class="wow fadeInUp">
    <div class="float-right"> 
      <a type="button" class="btn btn-info" href="{{ url_for('songs.new_song') }}"><i class="fa fa-plus"></i> Add New</a>   
    </div>
    <div class="table-responsive">
      <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Artist</th>
          {% if current_user.is_authenticated %}
            <th scope="col">Options</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
      {% for song in song_list.items %}
        <tr >
          <td>{{ song.name }}</td>
          <td>{{ song.artist }}</td>
          {% if current_user.is_authenticated %}
            <td><a title="Delete" class="btn btn-danger btn-sm mt-1 mb-1" href="{{ url_for('songs.delete_song', song_id=song.id) }}"><i class="fa fa-trash"></i></a> </td>
          {% endif %}
        </tr>
      {% endfor %}
          
      </tbody>
      </table>

    </div>
    {% for page_num in song_list.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if song_list.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('songs.song_request', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('songs.song_request', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}